apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: tasker
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m" 