apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasker
  namespace: tasker
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: tasker
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m" 