apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tasker-app

namespace: tasker

resources:
  - postgres-namespace.yaml
  - postgres-secret.yaml
  - postgres-configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - tasker-configmap.yaml
  - tasker-deployment.yaml
  - tasker-service.yaml

images:
  - name: postgres
    newTag: "15-alpine"
  - name: tasker
    newName: ghcr.io/neatflowcv/tasker
    newTag: latest

commonLabels:
  app: tasker
  version: v1

patchesStrategicMerge:
  - patches/postgres-resources.yaml
  - patches/tasker-resources.yaml
